version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: msadoc
    ports:
      - 5432:5432

  adminer:
    # use "db" as host as it uses Docker internal DNS
    image: adminer
    restart: always
    ports:
      - 5433:8080