name: CI Pipeline

defaults:
  run:
    working-directory: server

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    name: msadoc server
      
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm i

      - name: Run build scripts
        run: npm run build

      - name: Run the linter
        run: npm run lint

      - name: Run test scripts
        run: npm run test

      - name: Run e2e tests
        run: |
          docker compose -f docker-compose.ci.yaml build
          cp .env.ci .env
          docker compose -f docker-compose.ci.yaml up -d
          npm run test:e2e
          docker compose -f docker-compose.ci.yaml down
